In [2]:
import numpy as np

In [47]:
# Back substitute an upper triangular matrix A
def back_sub(A, b):
    # Result
    x = []
    for i in range(len(A)):
        r = len(A) - i - 1 
        xi = (b[r][0] - sum([A[r][-j-1] * x[-j-1] for j in range(0, i)])) / A[r][r] 
        x.insert(0, xi)
        
    return np.transpose(x)
    

In [49]:
A = np.array([[3, 1], [2, 3]], dtype=np.float64)
b = np.array([[14/3], [7/3]], dtype=np.float64)
 
A[1] = A[1] - (A[0] * 2 / 3.0)
b[1] = b[1] - (b[0] * 2 / 3.0) 

print(back_sub(A, b))

[ 1.66666667 -0.33333333]


In [53]:
import scipy

A = np.array([[1,2,3],[2,5,8],[3,8,14]])
# LU sub
res = scipy.linalg.lu(A)
res

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.33333333, 1.        , 0.        ],
        [0.66666667, 0.5       , 1.        ]]),
 array([[ 3.        ,  8.        , 14.        ],
        [ 0.        , -0.66666667, -1.66666667],
        [ 0.        ,  0.        , -0.5       ]]))

In [97]:

# Jacobi
# Run jacobi iteration
def jacobi_iter(x, A, b, n=20):
    D = np.array([[A[i][j] if i == j else 0 for i in range(len(A))] for j in range(len(A))])
    D_inv = np.array([[1/A[i][j] if i == j else 0 for i in range(len(A))] for j in range(len(A))])
    for i in range(0, n):
        # Show stats
        norm = np.sqrt(np.sum((b - A.dot(x)) ** 2))
        print(f"Iteration [{i}], err={norm}:\nx={x}\n")
        
        # Iterate
        x = x + D_inv.dot(b - A.dot(x))
    return x

In [89]:
A = np.array([[3, 1], [2, 3]])
b = np.array([[14/3], [7/3]])
x = np.zeros(b.shape)
jacobi_iter(x, A, b)


[[3 0]
 [0 3]]
Iteration [0], err=5.21749194749951:
x=[[0.]
 [0.]]

Iteration [1], err=3.2068599310359582:
x=[[1.55555556]
 [0.77777778]]

Iteration [2], err=1.159442654999891:
x=[[ 1.2962963 ]
 [-0.25925926]]

Iteration [3], err=0.7126355402302128:
x=[[ 1.64197531]
 [-0.08641975]]

Iteration [4], err=0.25765392333330894:
x=[[ 1.58436214]
 [-0.31687243]]

Iteration [5], err=0.15836345338449173:
x=[[ 1.6611797 ]
 [-0.27846365]]

Iteration [6], err=0.05725642740740187:
x=[[ 1.64837677]
 [-0.32967535]]

Iteration [7], err=0.03519187852988679:
x=[[ 1.66544734]
 [-0.32114007]]

Iteration [8], err=0.012723650534978436:
x=[[ 1.66260225]
 [-0.33252045]]

Iteration [9], err=0.007820417451086263:
x=[[ 1.66639571]
 [-0.33062372]]

Iteration [10], err=0.002827477896661588:
x=[[ 1.66576346]
 [-0.33315269]]

Iteration [11], err=0.0017378705446857408:
x=[[ 1.66660645]
 [-0.3327312 ]]

Iteration [12], err=0.0006283284214813459:
x=[[ 1.66646595]
 [-0.33329319]]

Iteration [13], err=0.000386193454375015

In [91]:
# Midpoint
def midpoint_iter(y_0, dy, dx, x_0 = 0, n_steps = 10):
    y = y_0
    x = x_0
    for i in range(n_steps):
        print(f"Iteration [{i}]: x={x}, y={y}\n")
        dy_half = dy(x, y)
        mid_y = y + dy_half * dx/2
        mid_x = x + dx/2
        mid_dy = dy(mid_x, mid_y)
        y += dx * mid_dy 
        x += dx
    return y
        

In [96]:
y_0 = 1
dy = lambda x, y: -y*y + x*x
print(midpoint_iter(y_0, dy, 0.5))

Iteration [0]: x=0, y=1

Iteration [1]: x=0.5, y=0.75

Iteration [2]: x=1.0, y=0.8055419921875

Iteration [3]: x=1.5, y=1.1877838991934297

Iteration [4]: x=2.0, y=1.742424209958086

Iteration [5]: x=2.5, y=2.3067093007287935

Iteration [6]: x=3.0, y=2.864743610846767

Iteration [7]: x=3.5, y=3.454841802552101

Iteration [8]: x=4.0, y=4.243779483349414

Iteration [9]: x=4.5, y=6.276129409765651

16.44557153094636


In [141]:
# Split a matrix into D, L, U
def gauss_seidel_split(x):
    D = np.array([[x[j][i] if i == j else 0 for i in range(len(x))] for j in range(len(x))])
    L = np.array([[x[j][i] if i < j else 0 for i in range(len(x))] for j in range(len(x))])
    U = np.array([[x[j][i] if i > j else 0 for i in range(len(x))] for j in range(len(x))])
    return D, L, U

# Gauss seidel iteration on a matrix
def gauss_seidel_iter(x, A, b, n=20):
    D, L, U = gauss_seidel_split(A)
    D_L_inv = np.linalg.inv(D + L)  
    for i in range(0, n):
        # Show stats
        norm = np.sqrt(np.sum((b - A.dot(x)) ** 2))
        print(f"Iteration [{i}], err={norm}:\nx={x}\n")
        
        # Iterate 
        x = x + D_L_inv.dot(b - A.dot(x))
    return x

In [142]:
A = np.array([[2, -1, 0], [-1, 1, 3], [1, 0, 1]], dtype=np.float64)
b = np.array([[1], [3], [2]], dtype=np.float64)
D, L, U = gauss_seidel_iter(np.array([[0], [0], [0]], dtype=np.float64), A, b)
jacobi_iter(np.array([[0], [0], [0]], dtype=np.float64), A, b)

Iteration [0], err=3.7416573867739413:
x=[[0.]
 [0.]
 [0.]]

Iteration [1], err=5.70087712549569:
x=[[0.5]
 [3.5]
 [1.5]]

Iteration [2], err=5.926634795564849:
x=[[ 2.25]
 [ 0.75]
 [-0.25]]

Iteration [3], err=5.659615711335886:
x=[[0.875]
 [4.625]
 [1.125]]

Iteration [4], err=6.210500181144833:
x=[[ 2.8125]
 [ 2.4375]
 [-0.8125]]

Iteration [5], err=5.747451881051289:
x=[[1.71875]
 [7.15625]
 [0.28125]]

Iteration [6], err=7.137906347890115:
x=[[ 4.078125]
 [ 6.234375]
 [-2.078125]]

Iteration [7], err=6.76012875767263:
x=[[ 3.6171875]
 [12.8515625]
 [-1.6171875]]

Iteration [8], err=10.110873693489753:
x=[[ 6.92578125]
 [14.77734375]
 [-4.92578125]]

Iteration [9], err=11.265327354446121:
x=[[ 7.88867188]
 [25.66601562]
 [-5.88867188]]

Iteration [10], err=18.335925485406296:
x=[[ 13.33300781]
 [ 33.99902344]
 [-11.33300781]]

Iteration [11], err=24.009743312129288:
x=[[ 17.49951172]
 [ 54.49853516]
 [-15.49951172]]

Iteration [12], err=38.24979257371546:
x=[[ 27.74926758]
 [ 77.24

array([[-32.77441406],
       [-73.57324219],
       [ 18.70214844]])

In [163]:

# Least squares - return coefficients
def best_fit(x, y):
    xT_x_inv = np.linalg.inv(x.T.dot(x))
    m = xT_x_inv.dot(x.T.dot(y))
    return m

In [164]:
x = np.array([0, 1, 2])
y = np.array([1.01, -0.05, 1.03])
A = np.concatenate([np.transpose([x]), np.transpose([x])**2, np.ones((len(x), 1))], axis=1)
print(best_fit(A, y.T))

[-2.13  1.07  1.01]


In [176]:
# 
t = np.array([[-1, 0, 1]]).T
y = np.array([[0.5, 1.2, 1.5]]).T

# Linear
A = np.concatenate([t, np.ones((len(t), 1))], axis=1)
m = best_fit(A, y)
print(m)
print("MSE", np.mean((A.dot(m) - y)**2))
y_2 = np.array([[2, 1]]).dot(m)
print(y_2)
print("\n")

# Quadratic
A = np.concatenate([t, t**2, np.ones((len(t), 1))], axis=1)
m = best_fit(A, y)
print(m)
print("MSE", np.mean((A.dot(m) - y)**2))
y_2 = np.array([[2, 4, 1]]).dot(m)
print(y_2)

[[0.5       ]
 [1.06666667]]
MSE 0.008888888888888885
[[2.06666667]]


[[ 0.5]
 [-0.2]
 [ 1.2]]
MSE 1.6434602192104412e-32
[[1.4]]
